<!DOCTYPE html>
<html lang="ru">
  <head>
   
  </head>
  <body>
    <h1><b> Войти </b> </h1>
    <form action = "/check" method = "post">
    Логин: <input type = "text" name = "login"/> <br><br>
    Пароль: <input type = "text" name = "password"/> <br><br>

    <input type = "submit" value = "Войти"/>

 </form>
 
 <h1><b> Регаться </b> </h1>
    <form action = "/registration" method = "post">
    Логин: <input type = "text" name = "login"/> <br><br>
    Пароль: <input type = "text" name = "password"/> <br><br>
   

    <input type = "submit" value = "Зарегаться"/>

 </form>
 
      </body>
</html>